{{/*
Expand the name of the chart.
*/}}
{{- define "food-freenzy-helm.name" -}}
{{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" -}}
{{- end }}

{{/*
Create a fully qualified name.
*/}}
{{- define "food-freenzy-helm.fullname" -}}
{{- if .Values.fullnameOverride -}}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- $name := default .Chart.Name .Values.nameOverride -}}
{{- if contains $name .Release.Name -}}
{{- .Release.Name | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" -}}
{{- end -}}
{{- end -}}
{{- end }}

{{/*
Chart label.
*/}}
{{- define "food-freenzy-helm.chart" -}}
{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" -}}
{{- end }}

{{/*
Common labels.
*/}}
{{- define "food-freenzy-helm.labels" -}}
helm.sh/chart: {{ include "food-freenzy-helm.chart" . }}
app.kubernetes.io/name: {{ include "food-freenzy-helm.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
{{- if .Chart.AppVersion }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
{{- end }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}

{{/*
Selector labels.
*/}}
{{- define "food-freenzy-helm.selectorLabels" -}}
app.kubernetes.io/name: {{ include "food-freenzy-helm.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}

{{/*
ServiceAccount name.
*/}}
{{- define "food-freenzy-helm.serviceAccountName" -}}
{{- if .Values.serviceAccount.create -}}
{{- default (include "food-freenzy-helm.fullname" .) .Values.serviceAccount.name -}}
{{- else -}}
{{- default "default" .Values.serviceAccount.name -}}
{{- end -}}
{{- end }}

{{/* =========================
   MySQL helpers
   ========================= */}}

{{/*
MySQL resource name.
*/}}
{{- define "food-freenzy-helm.mysql.name" -}}
{{- printf "%s-mysql" (include "food-freenzy-helm.fullname" .) -}}
{{- end }}

{{/*
MySQL labels.
*/}}
{{- define "food-freenzy-helm.mysql.labels" -}}
helm.sh/chart: {{ include "food-freenzy-helm.chart" . }}
app.kubernetes.io/name: {{ include "food-freenzy-helm.name" . }}-mysql
app.kubernetes.io/instance: {{ .Release.Name }}
app.kubernetes.io/component: mysql
app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}

{{/*
MySQL selector labels.
*/}}
{{- define "food-freenzy-helm.mysql.selectorLabels" -}}
app.kubernetes.io/name: {{ include "food-freenzy-helm.name" . }}-mysql
app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
