apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "food-freenzy-helm.fullname" . }}
  labels:
    {{- include "food-freenzy-helm.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{- include "food-freenzy-helm.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{- include "food-freenzy-helm.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "food-freenzy-helm.fullname" . }}
          image: "{{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}"
          imagePullPolicy: {{ .Values.mysql.image.pullPolicy }}
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              value: {{ .Values.mysql.database }}
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "food-freenzy-helm.fullname" . }}
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "food-freenzy-helm.fullname" . }}
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "food-freenzy-helm.fullname" . }}
                  key: MYSQL_PASSWORD
