# ============================
# SPRINGBOOT APP DEPLOYMENT
# ============================
app:
  name: foodfrenzy
  replicas: 2

  image:
    repository: sunilkumar45/foodfrenzyapp
    tag: "v1.0.0"
    pullPolicy: Always

  port: 8083

# ============================
# MYSQL DEPLOYMENT
# ============================
mysql:
  enabled: true

  image:
    repository: mysql
    tag: "8.0"
    pullPolicy: IfNotPresent

  service:
    port: 3306

  database: food_frenzy_db

# ============================
# SECRETS
# ============================
secret:
  mysql:
    rootPassword: "root123"
    user: "appuser"
    password: "apppass"

# ============================
# SERVICE
# ============================
service:
  type: ClusterIP
  port: 80

# ============================
# INGRESS
# ============================
ingress:
  enabled: true
  host: foodfrenzy.local
  path: /

# =====================
# Service Account
# =====================
serviceAccount:
  create: true
  name: ""

httpRoute:
  enabled: false

