#============================
# SPRINGBOOT APP DEPLOYMENT
#============================
app:
  name: foodfrenzy
  replicas: 2
  image:
    repository: sunilkumar45/foodfrenzyapp
    tag: v1.0.0
    pullPolicy: Always
  port: 8083

  #===============================
  # MYSQL DEPLOYMENT
  #===============================
mysql:
  image: mysql
    tag: "8.0"
    pullPolicy: IfNotPresent
  service:
    port: 3306
  database: food_frenzy_db
  
#===============================
# SECRET 
#===============================   
secret:
  mysql:
    rootPassword: root123
    user: appuser
    password: apppass

# =====================
# Service
# =====================
service:
  type: ClusterIP
  port: 80

# =====================
# Ingress
# =====================
ingress:
  enabled: true
  host: foodfrenzy.local
  path: /